import { Game } from '@/types/game';

export interface ExtendedGame extends Game {
  rating?: number;
}

export const BASE_GAMES_CATALOG: ExtendedGame[] = [
  // 1. Classic Platform Originals
  {
    id: 'space-gem-collector',
    slug: 'space-gem-collector',
    title: 'Space Gem Collector',
    description: 'Pilot your ship through deep space, dodge cosmic hazards, and harvest glowing energy gems in this fast-paced 60 FPS arcade collector.',
    category: 'arcade',
    tags: ['arcade', 'space', 'retro', '2d', 'casual', 'high score'],
    dimensions: { width: 800, height: 500 },
    orientation: 'landscape',
    controls: 'Use Mouse or Arrow Keys / WASD to steer the ship and collect gems.',
    entryUrl: '/games/test-game/index.html',
    thumbnailUrl: '/thumbnails/space-gem-collector.svg',
    developer: { name: 'Platform Studio', websiteUrl: 'https://arcadehub.com' },
    publishedAt: '2026-08-30T00:00:00Z',
    rating: 4.8,
    playTimeMinutes: 3,
    moods: ['quick', 'competitive'],
    inputs: ['touch', 'keyboard', 'mouse'],
    isMobileFriendly: true,
    featuredBadge: '60 FPS Space Gem',
    leaderboard: {
      enabled: true,
      scoreType: 'highest',
      scoringMode: 'points',
      maxRatePerSec: 150,
      unitLabel: 'PTS',
    },
  },
  {
    id: 'cyber-track-2026',
    slug: 'cyber-track-2026',
    title: 'Cyber Track 2026',
    description: 'High-speed neon highway racing. Dodge hyper-speed traffic, push your vehicle past 180 MPH, and set new platform distance records.',
    category: 'racing',
    tags: ['racing', 'cyberpunk', 'retro', 'speed', 'synthwave'],
    dimensions: { width: 800, height: 500 },
    orientation: 'landscape',
    controls: 'Use Left/Right Arrow Keys, A/D, or Touch Tap to steer across lanes.',
    entryUrl: '/games/cyber-track-2026/index.html',
    thumbnailUrl: '/thumbnails/speed-racing.svg',
    developer: { name: 'HyperDrive Studio', websiteUrl: 'https://arcadehub.com' },
    publishedAt: '2026-09-01T00:00:00Z',
    rating: 4.9,
    playTimeMinutes: 4,
    moods: ['challenging', 'quick', 'competitive'],
    inputs: ['touch', 'keyboard'],
    isMobileFriendly: true,
    featuredBadge: 'Neon Speed',
    leaderboard: {
      enabled: true,
      scoreType: 'highest',
      scoringMode: 'distance',
      maxRatePerSec: 250,
      unitLabel: 'PTS',
    },
  },
  {
    id: 'neon-grid-breaker',
    slug: 'neon-grid-breaker',
    title: 'Neon Grid Breaker',
    description: 'Synthwave-infused brick deconstruction. Control the quantum paddle, shatter neon energy blocks, and clear multi-colored grid matrices.',
    category: 'puzzle',
    tags: ['puzzle', 'breakout', 'arcade', 'retro', 'physics'],
    dimensions: { width: 800, height: 500 },
    orientation: 'landscape',
    controls: 'Use Mouse Movement, Touch Drag, or Left/Right Arrow Keys to control the paddle.',
    entryUrl: '/games/neon-grid-breaker/index.html',
    thumbnailUrl: '/thumbnails/block-puzzle.svg',
    developer: { name: 'Quantum Block Labs', websiteUrl: 'https://arcadehub.com' },
    publishedAt: '2026-09-01T12:00:00Z',
    rating: 4.7,
    playTimeMinutes: 5,
    moods: ['relaxing', 'quick'],
    inputs: ['touch', 'keyboard', 'mouse'],
    isMobileFriendly: true,
    featuredBadge: 'Retro Synth',
    leaderboard: {
      enabled: true,
      scoreType: 'highest',
      scoringMode: 'points',
      maxRatePerSec: 200,
      unitLabel: 'PTS',
    },
  },
  {
    id: 'void-runner',
    slug: 'void-runner',
    title: 'Void Runner',
    description: 'Defy physics in a gravity-flipping cyber universe. Invert gravity to run along ceilings, evade lasers, and sprint through the endless void.',
    category: 'action',
    tags: ['action', 'runner', 'gravity', 'fast-paced', 'cyber'],
    dimensions: { width: 800, height: 500 },
    orientation: 'landscape',
    controls: 'Press Space, Up Arrow, W, or Tap Screen to flip gravity between floor and ceiling.',
    entryUrl: '/games/void-runner/index.html',
    thumbnailUrl: '/thumbnails/neon-runner.svg',
    developer: { name: 'Void Dynamic Games', websiteUrl: 'https://arcadehub.com' },
    publishedAt: '2026-09-02T00:00:00Z',
    rating: 4.9,
    playTimeMinutes: 4,
    moods: ['challenging', 'competitive'],
    inputs: ['touch', 'keyboard', 'mouse'],
    isMobileFriendly: true,
    featuredBadge: 'Gravity Flip',
    leaderboard: {
      enabled: true,
      scoreType: 'highest',
      scoringMode: 'distance',
      maxRatePerSec: 200,
      unitLabel: 'M',
    },
  },

  // 2. Curated .IO Multiplayer Arena Games
  {
    id: 'cyber-battle-io',
    slug: 'cyber-battle-io',
    title: 'Cyber Battle .IO',
    description: 'Enter the neon battle arena! Outmaneuver global players, deploy plasma blasters, and conquer the cyber grid in intense real-time multiplayer combat.',
    category: 'battle',
    tags: ['io', 'multiplayer', 'battle', 'shooting', 'arena', 'pvp'],
    dimensions: { width: 900, height: 600 },
    orientation: 'landscape',
    controls: 'WASD / Arrow Keys to move, Mouse Cursor to aim, Left Click to fire blasters.',
    entryUrl: '/games/test-game/index.html',
    thumbnailUrl: '/thumbnails/space-gem-collector.svg',
    developer: { name: 'ArenaHub Studios', websiteUrl: 'https://arcadehub.com' },
    publishedAt: '2026-09-02T12:00:00Z',
    rating: 4.95,
    playTimeMinutes: 6,
    moods: ['competitive', 'challenging'],
    inputs: ['touch', 'keyboard', 'mouse'],
    isMobileFriendly: true,
    featuredBadge: 'Featured .IO Arena',
    isIoGame: true,
    multiplayerMode: 'battle-royale',
    basePlayerCount: 1480,
    serverRegions: ['US-East', 'EU-West', 'AP-South'],
    isTrendingIo: true,
    leaderboard: {
      enabled: true,
      scoreType: 'highest',
      scoringMode: 'points',
      maxRatePerSec: 300,
      unitLabel: 'KILLS',
    },
  },
  {
    id: 'orbit-clash-io',
    slug: 'orbit-clash-io',
    title: 'Orbit Clash .IO',
    description: 'High-speed orbital dogfights. Absorb planetary energy cores, boost past asteroid fields, and eliminate rival pilots to rule the sector.',
    category: 'shooting',
    tags: ['io', 'shooting', 'space', 'pvp', 'multiplayer'],
    dimensions: { width: 900, height: 600 },
    orientation: 'landscape',
    controls: 'Mouse to direct orbit trajectory, Spacebar to activate hyper-thrust, Click to shoot.',
    entryUrl: '/games/void-runner/index.html',
    thumbnailUrl: '/thumbnails/neon-runner.svg',
    developer: { name: 'Orbital Kinetics', websiteUrl: 'https://arcadehub.com' },
    publishedAt: '2026-09-02T14:00:00Z',
    rating: 4.88,
    playTimeMinutes: 5,
    moods: ['competitive', 'quick'],
    inputs: ['touch', 'keyboard', 'mouse'],
    isMobileFriendly: true,
    featuredBadge: 'Orbital Arena',
    isIoGame: true,
    multiplayerMode: 'ffa',
    basePlayerCount: 920,
    serverRegions: ['GLOBAL'],
    isTrendingIo: true,
  },
  {
    id: 'grid-survivor-io',
    slug: 'grid-survivor-io',
    title: 'Grid Survivor .IO',
    description: 'Survive in an expanding neon wasteland against swarms of rogue algorithms and hostile player drones.',
    category: 'survival',
    tags: ['io', 'survival', 'action', 'multiplayer', 'roguelike'],
    dimensions: { width: 850, height: 550 },
    orientation: 'landscape',
    controls: 'WASD or Virtual Joystick to evade, auto-target nearby hostiles.',
    entryUrl: '/games/neon-grid-breaker/index.html',
    thumbnailUrl: '/thumbnails/block-puzzle.svg',
    developer: { name: 'Quantum Core', websiteUrl: 'https://arcadehub.com' },
    publishedAt: '2026-09-02T15:00:00Z',
    rating: 4.82,
    playTimeMinutes: 8,
    moods: ['challenging', 'competitive'],
    inputs: ['touch', 'keyboard'],
    isMobileFriendly: true,
    isIoGame: true,
    multiplayerMode: 'co-op',
    basePlayerCount: 1140,
    serverRegions: ['EU-West', 'AP-South'],
  },
  {
    id: 'hyper-drift-io',
    slug: 'hyper-drift-io',
    title: 'Hyper Drift .IO',
    description: 'Multiplayer drifting battles on neon speedways. Overtake live opponents, time slipstreams, and dominate the global leaderboards.',
    category: 'racing',
    tags: ['io', 'racing', 'drift', 'multiplayer', 'pvp'],
    dimensions: { width: 850, height: 550 },
    orientation: 'landscape',
    controls: 'Left/Right Keys or Screen Tap to drift smoothly through tight hairpin curves.',
    entryUrl: '/games/cyber-track-2026/index.html',
    thumbnailUrl: '/thumbnails/speed-racing.svg',
    developer: { name: 'HyperDrive Studio', websiteUrl: 'https://arcadehub.com' },
    publishedAt: '2026-09-02T16:00:00Z',
    rating: 4.9,
    playTimeMinutes: 4,
    moods: ['quick', 'competitive'],
    inputs: ['touch', 'keyboard'],
    isMobileFriendly: true,
    isIoGame: true,
    multiplayerMode: '1v1',
    basePlayerCount: 840,
    serverRegions: ['US-East', 'EU-West'],
    isTrendingIo: true,
  },
  {
    id: 'pixel-snake-io',
    slug: 'pixel-snake-io',
    title: 'Pixel Snake .IO',
    description: 'The multiplayer classic reinvented with glowing particle trails, power boosts, and dynamic arena shrinking zones.',
    category: 'action',
    tags: ['io', 'snake', 'classic', 'multiplayer', 'arcade'],
    dimensions: { width: 800, height: 500 },
    orientation: 'landscape',
    controls: 'Mouse or Finger Swipe to direct the snake path, Click/Hold to speed boost.',
    entryUrl: '/games/test-game/index.html',
    thumbnailUrl: '/thumbnails/space-gem-collector.svg',
    developer: { name: 'Retrobyte Games', websiteUrl: 'https://arcadehub.com' },
    publishedAt: '2026-09-02T17:00:00Z',
    rating: 4.75,
    playTimeMinutes: 5,
    moods: ['quick', 'relaxing'],
    inputs: ['touch', 'keyboard', 'mouse'],
    isMobileFriendly: true,
    isIoGame: true,
    multiplayerMode: 'ffa',
    basePlayerCount: 2350,
    serverRegions: ['GLOBAL'],
  },
  {
    id: 'tactic-board-io',
    slug: 'tactic-board-io',
    title: 'Tactic Board .IO',
    description: 'Fast-paced turn-based tactical board warfare. Outsmart online challengers in rapid 3-minute tactical battles.',
    category: 'board',
    tags: ['io', 'board', 'strategy', 'turn-based', 'pvp'],
    dimensions: { width: 800, height: 500 },
    orientation: 'landscape',
    controls: 'Click/Tap pieces and select target nodes to move or attack.',
    entryUrl: '/games/neon-grid-breaker/index.html',
    thumbnailUrl: '/thumbnails/block-puzzle.svg',
    developer: { name: 'MindGrid Labs', websiteUrl: 'https://arcadehub.com' },
    publishedAt: '2026-09-02T18:00:00Z',
    rating: 4.86,
    playTimeMinutes: 4,
    moods: ['challenging', 'relaxing'],
    inputs: ['touch', 'mouse'],
    isMobileFriendly: true,
    isIoGame: true,
    multiplayerMode: '1v1',
    basePlayerCount: 670,
    serverRegions: ['GLOBAL'],
  },
];

export function getAllGames(): ExtendedGame[] {
  if (typeof window === 'undefined') {
    return BASE_GAMES_CATALOG;
  }

  try {
    const customRaw = localStorage.getItem('arcadehub_creator_games_db');
    if (customRaw) {
      const customGames: any[] = JSON.parse(customRaw);
      const formattedCustom: ExtendedGame[] = customGames.map((cg) => ({
        id: cg.id,
        slug: cg.slug || cg.id,
        title: cg.title,
        description: cg.description || 'Community Creator Title',
        category: (cg.category as any) || 'arcade',
        tags: cg.tags || ['creator', 'arcade'],
        dimensions: cg.dimensions || { width: 800, height: 500 },
        orientation: cg.orientation || 'landscape',
        controls: cg.controls || 'Use Mouse / Keyboard to play.',
        entryUrl: cg.entryUrl || '/games/test-game/index.html',
        thumbnailUrl: cg.thumbnailUrl || '/thumbnails/space-gem-collector.svg',
        developer: { name: cg.studioName || 'Independent Studio', websiteUrl: 'https://arcadehub.com' },
        publishedAt: cg.submittedAt || new Date().toISOString(),
        rating: 5.0,
        playTimeMinutes: 5,
        moods: ['quick', 'challenging'],
        inputs: ['keyboard', 'mouse'],
        isMobileFriendly: true,
        isIoGame: cg.isIoGame || false,
        leaderboard: cg.leaderboard || {
          enabled: true,
          scoreType: 'highest',
          scoringMode: 'points',
          unitLabel: 'PTS',
        },
      }));

      const existingIds = new Set(BASE_GAMES_CATALOG.map((g) => g.id));
      const filteredCustom = formattedCustom.filter((g) => !existingIds.has(g.id));
      return [...BASE_GAMES_CATALOG, ...filteredCustom];
    }
  } catch (e) {}

  return BASE_GAMES_CATALOG;
}

export function getGameBySlug(slug: string): ExtendedGame | undefined {
  const games = getAllGames();
  return games.find((game) => game.slug === slug || game.id === slug);
}

export function getIoArenaGames(): ExtendedGame[] {
  const games = getAllGames();
  return games.filter((g) => g.isIoGame || g.tags?.includes('io'));
}